### ISSUE TITLE
quoting style

### ISSUE THREAD

**Issue by not-my-profile** [undersquire/undersquire#1]
Hey, thanks for participating in the RFC discussion :)

I'm curious why do you tend to use the "Quote Reply" feature of GitHub?

Personally I find it really annoying if somebody writes a long comment and you quote all of it at the beginning of your comment ... just makes the whole thread twice as long as it needs to be^^

**Comment by undersquire** [comment]
I just do it out of habit to signify who I am replying to 😂
I can remove some of the longer quotes to shorten the discussion if you'd like.

EDIT: I modified my messages with the large quotes to just quote the part I wanted to quote. I'll do that from now on
